### ISSUE TITLE
Different problems on Mac

### ISSUE THREAD

**Issue by yann-ledu** [jakwings/vim-pony#1]
Hi, I've got problems using the vim-pony plugin
I'm on mac, with vim installed by brew, latest upgrade, VIM - Vi IMproved 7.4 (2013 Aug 10, compiled Jun 5 2016 00:55:29)
First, I get:

Error detected while processing /Users/yann/.vim/bundle/vim-pony/ftplugin/pony.vim:
line 16:
E539: Illegal character <j>: formatoptions+=croqlj

That's ok, I can just either remove j or silence the command, even though I should check what j does...
But that said, there remains problems: 1/ vim hangs when I use the pony mode sometimes, and  I have to use C-c. And 2/ I get no automatic indent.

My .vimrc is here: https://gist.github.com/yann-ledu/691c95100178da8547a3c1f35f18e490

apparently some config options i have, and maybe other plugins, conflict 

Here's my bundle directory :

Dockerfile/         pony-vim-syntax/    syntastic/          vim-fireplace/      vim-unimpaired/
neocomplcache/      racer/              unite.vim/          vim-hdevtools/      vimproc.vim/
nimrod.vim/         rust.vim/           vim-clojure-static/ vim-surround/       vimshell/

**Comment by jakwings** [comment]
Seems that I'm using the same version of vim.

According to the vim manual, `formatoptions+=croqlj` is indeed invalid, I should add one flag at a time. You can also check if `j` is a valid flag in `help 'fo-table'`.

> vim hangs when I use the pony mode sometimes, and I have to use C-c

Are you editing a large file, maybe vim is removing trailing spaces in the whole file.
See https://github.com/jakwings/vim-pony/blob/6d33ce36fc002227f89168f2f7aecacda8baa8dc/indent/pony.vim#L23-L26
Only CursorHold and BufWritePre will trigger global action.

> I get no automatic indent.

Try `:echo &lisp &cindent &autoindent &smartindent &indent
indentexpr  indentkeys`, can you see:

```
0 0 0 0 pony#Indent() !^F,o,O,0|,0(,0),0[,0],0{,0},0==>,0=end,0=then,0=else,0=in,0=do,0=until,0=acto
r,0=class,0=struct,0=primitive,0=trait,0=interface,0=new,0=be,0=fun,0=type,0=use
```
