### ISSUE TITLE
Syntax highlighting of methods with explicit receiver capability

### ISSUE THREAD

**Issue by Praetonus** [jakwings/vim-pony#2]
![scr](https://cloud.githubusercontent.com/assets/5193706/15892391/b5aaf976-2d79-11e6-9167-35844d62460b.jpg)

Here, the `reserve` method has an explicit receiver capability and isn't highlighted correctly.

**Comment by jakwings** [comment]
<img width="364" alt="2016-06-08" src="https://cloud.githubusercontent.com/assets/1451509/15894011/f7bdd8ba-2db5-11e6-8965-f162f0ec0696.png">

Ok, now fixed.

**Comment by Praetonus** [comment]
Thanks!
